import fs from 'fs';
import path from 'path';
import { validateZine } from './validation.mjs';

const ZINES_DIR = path.join(process.cwd(), 'public/zines');
const OUTPUT_FILE = path.join(process.cwd(), 'src/data/zines/index.ts');

async function syncZines() {
  console.log('Syncing zines from public/zines...');

  if (!fs.existsSync(ZINES_DIR)) {
    console.error(`Directory not found: ${ZINES_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(ZINES_DIR).filter(file => file.endsWith('.json'));
  const zines = [];
  let hasErrors = false;

  for (const file of files) {
    const filePath = path.join(ZINES_DIR, file);
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const zine = JSON.parse(content);
      
      const validationErrors = validateZine(zine, file);
      if (validationErrors.length > 0) {
        console.error(`\nValidation errors in ${file}:`);
        validationErrors.forEach(err => console.error(`  - ${err}`));
        hasErrors = true;
      } else {
        zines.push(zine);
        console.log(`- Loaded ${zine.slug || file}`);
      }
    } catch (err) {
      console.error(`Error parsing ${file}:`, err.message);
      hasErrors = true;
    }
  }

  if (hasErrors) {
    console.error('\nSync failed due to validation errors.');
    process.exit(1);
  }

  const outputContent = `// Auto-generated by scripts/sync-zines.mjs
import { Zine } from '@/types/zine';

export const allZines: Zine[] = ${JSON.stringify(zines, null, 2)} as Zine[];

// Collect all unique asset paths for prefetching
export const zineAssetUrls: string[] = Array.from(
  new Set(
    allZines.flatMap(zine => 
      zine.pages.flatMap(page => 
        page.blocks.flatMap(block => {
          if ('image' in block && block.image?.asset_path) {
            return [block.image.asset_path];
          }
          return [];
        })
      )
    )
  )
);
`;

  fs.writeFileSync(OUTPUT_FILE, outputContent);
  console.log(`\nSuccessfully synced ${zines.length} zines to ${OUTPUT_FILE}`);
}

syncZines();
